kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: havi-image-access
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ota-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
