kind: Job
apiVersion: batch/v1
metadata:
  name: post-commit-build-havi
  namespace: havi
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: start-tekton-pipeline
          image: gcr.io/tekton-releases/dogfooding/tkn:latest
          command:
          - tkn
          - pipeline
          - start
          - build-and-run
      serviceAccountName: pipeline
      restartPolicy: OnFailure
